version: '3.9'
services:
  flaskapp:
    build:
      context: ./docker_API_image
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - ./docker_API_image/employees_API:/employees_API    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: employees
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  centos:
    build: 
      context: ./docker_centos
      dockerfile: Dockerfile.dev
     
    links:
      - db
    depends_on:
      - db